### PR TITLE
fix(constraints-api): don't read from db for checking proposer duties

### LINKED ISSUE #13: perf: avoid calling the db on every constraint submission
As outlined here:

https://github.com/chainbound/helix/blob/afdcb8b724f7390dbb0196ff368fa9a3059b9355/crates/api/src/constraints/api.rs#L101

it would be great to cache the proposer duties in the constraints API as to not fetch from the db every time a new 
submission comes in.

### PR DESCRIPTION
**Pull request by thedevbirb**
This PR drops the DB requirement for running the constraints API, and relies on the chain event updater for receiving proposer duties. The implementation matches what has been done in other apis, for example the proposer api.

Related discussion: https://github.com/gattaca-com/helix/pull/49#discussion_r1857212656
Closes #13 

Tested on devnet

### CODE REVIEW

File: crates/api/src/constraints/api.rs [hunk 1]
```diff
@@ -108,14 +134,18 @@ where
             return Err(ConstraintsApiError::InvalidConstraints)
         }
 
-        // PERF: can we avoid calling the db?
-        let maybe_validator_pubkey = api.db.get_proposer_duties().await?.iter().find_map(|d| {
-            if d.slot == first_constraints.slot {
-                Some(d.entry.registration.message.public_key.clone())
+        let maybe_validator_pubkey =
+            if let Some(duties) = api.curr_slot_info.read().await.new_duties.as_ref() {
```
Comment (merklefruit) [inline crates/api/src/constraints/api.rs:138]: are you sure we need the `tokio::sync` version of RwLock? It doesn't look like we're holding the lock through an await point. If `parking_lot` is available, I'd use that, and if not, perhaps the `std` lib one should be fine too

Comment (thedevbirb) [reply crates/api/src/constraints/api.rs:138]: You're right -- for the reason you mentioned and also because there is not much contention over the resource, `std::sync::RwLock` is probably faster. However in all the codebase `tokio::sync::RwLock` is used, so for consistency I'll keep it as it is.

**Review by merklefruit — APPROVED** [review]
LGTM
